//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockID { get; set; }
        public string StockTime { get; set; }
        public string StockName { get; set; }
        public string StockDeal { get; set; }
        public string StockBuy { get; set; }
        public string StockSell { get; set; }
        public string StockGainDrop { get; set; }
        public string StockShareCount { get; set; }
        public string StockYesterday { get; set; }
        public string StockOpen { get; set; }
        public string StockTop { get; set; }
        public string StockDown { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
