//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAngleSharp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Stock
    {
        public string Stock_ID { get; set; }
        public string Stock_Name { get; set; }
        public string Stock_Url { get; set; }
        public int Stock_Catetory_ID { get; set; }
    }
}
