//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAngleSharp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StockCompany
    {
        public string Stock_ID { get; set; }
        public string Company_Url { get; set; }
        public Nullable<int> Catetory_ID { get; set; }
        public string CompanyCreateDate { get; set; }
        public string StockCreateDate { get; set; }
        public string Stock_Capital { get; set; }
        public string Revenue { get; set; }
        public string Company_Official_Url { get; set; }
        public string Company_Fatory { get; set; }
    }
}
